### ISSUE TITLE
Question of about the provim pipeline?

### ISSUE THREAD

**Issue by PeifengJi** [Kawue/provim#6]
Hi @Kawue:
    I am running the provim pipeline and goes well through all the operations. But, here, I have a result of the pipeline.
    As mentioned in the README file. The workflow_pybasis.py generates one basis_processed_pybasis.h5 file (default name). I see that the fast_convert_hdf.py analyzes every sample stored in the basis_processed_pybasis.h5 and generates h5, ibd and imzML files for each sample.
  1. Is there any special reason of splitting  the merged file into separated files (also generate merged file by setting parameter --write_merge). 
  2. In the following steps, should I go on handling the merged file or the separated file (one sample for each).
  Thank you!

Regards,

Peifeng

**Comment by Kawue** [comment]
Hi Peifeng,

I created the --write_merge to enable a simultaneous picking on the mean spectrum of all data sets at once.
However, the artifact and matrix cleaner, as well as the image writer class does not support merged files. This also counts for any of my other tools. They are all build to handle only single sample files. This is because me and my parter from the department of biology have found no advantage of handling everything in one file, except "less files". So I would go with individual files in your case.
To save some typing work, you can process multiple files at once, e.g. by using wildcard annotations for the input statement.
However, if you use multiple steps of the pipeline, be careful to always use the dataset created by the last step. Usually you can delete the previous one, lets say you align the data, then you compute the matrix reduction, then you go for picking. You want to make sure to use the output of the matrix reduction for picking. After matrix reduction you might want to delete the data set that resulted from alignment and after picking you might want to delete the result of the matrix reduction. I just programmed it to hold everything for reproducibility.

If you run into issues chaining the different modules, a friend created a shell script for her meaasurements. If you need this, I can ask her to send it to you as kind of a blueprint.

Best regards,
Karsten

ps. regarding your last ticket, my colleague also thinks that the Orbitrap parameters should be fine.

**Comment by PeifengJi** [comment]
Thank for the quick explanation!  It resolves my questions.
Also ,thank you for the kindly help.  I have looked into the codes and chained the scripts into a python script.

Best regards,

Peifeng
