### ISSUE TITLE
New issue about import error of the /matrix_postprocessing.py module

### ISSUE THREAD

**Issue by PeifengJi** [Kawue/provim#7]
I have just finished the pipeline (step 3.1: automated_matrix_detection.py).

 This step resulted in 4 file (in the matrix directory), except for the png files, for each sample, for example:  wtPbs114_processed_simplified_artifacts.h5,  
wtPbs114_processed_simplified_cleaned.h5,  
wtPbs114_processed_simplified_embedding_cleaned.npy,  
wtPbs114_processed_simplified_matrix.h5.

However, when I run the next step matrix_postprocessing.py using the command:
python ~/Downloads/softs/provim/matrix_postprocessing.py -r matrix -s matrix_pos
It raise error: 

Directory was given. Every matching HDF5 file in the given directory will be used.
Traceback (most recent call last):
  File "/Users/peifengji/Downloads/softs/provim/matrix_postprocessing.py", line 44, in <module>
    matrixframe = pd.read_hdf(join(paths[idx], fnames[idx] + "_matrix" + ".h5"))
  File "/Users/peifengji/miniconda3/envs/spatial/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File matrix/wtPbs114_processed_simplified_cleaned_matrix.h5 does not exist

Ps: the *_processed_simplified.h5 generated by the fast_convert_hdf.py and matrix_preprocessing.py were output into the convert directory. Does it matter?

**Comment by Kawue** [comment]
If I recall everything correctly this is not an issue as long as you call the script correctly.
I do not have my old calls at hand, however, it should work as follows:
To read the data (-r parameter) you use a wildcard notation, i.e. your input is *simplified.h5, as the relevant files that should be processed end with *simplified.h5. You can also call the whole file name directly, but the wildcard is more efficient for multiple files in one folder. The save parameter (-s) should point towards a directory.

What you want is that the postprocessing processes the *_simplified.h5 with the *_simplified_matrix.h5 (and if selected the *_simplified_artifacts.h5).

Sorry, but like I said, the pipeline is not really polished atm.

I also HIGHLY recommend the interactive method. The automated often leads to imperfect results and in rare cases it can even lead to wrong results. It uses a approximation which is only trustworthy if the matrix pixels spectral characteristics are reasonable different from the remaining sample.

**Comment by PeifengJi** [comment]
Thank you!
Finally, I got the result. However, another question came out. 
In my design, I panned to query the difference between wt and ko mice in the aspect of metabolites. But, after peak picking step, I found that only a few metabolite were shared between any two samples. For example:

<img width="1040" alt="截屏2021-07-27 下午12 14 53" src="https://user-images.githubusercontent.com/86214818/127094404-0efb2c82-8710-4e7d-bdfe-1792096c53f6.png">

I thought there should be a large number of metabolites were shared between sample. Could you give me some hints about the low level of shared metabolites? 
PS: I have just run workflow_pybasis.py, fast_convert_hdf.py and workflow_peakpicking.py. Because in my experiment, I have performed derivatization to my samples and do not need to consider the impact of matrix.

Cmds as follows:
python ~/Downloads/softs/provim/workflow_pybasis.py -d HUI -s hui -i orbitrap  --multisample
python ~/Downloads/softs/provim/fast_convert_hdf.py -f basis/basis_processed_pybasis.h5 -s provim
python ~/Downloads/softs/provim/workflow_peakpicking.py -r provim/wtLm043_processed_simplified.h5 -s peakPickinghis

**Comment by Kawue** [comment]
Thats hard to say. In general, it might be worth to call the picking tool interactively to compare the mean spectra. I would assume, that there might be some minor shifts between the two samples. In the end, you pick on the mean spectrum for each sample. Especially with spectral high resolution, the mean could slightly shift some peaks, which would result in many differences.
To investigate this further, I would advice to look at both mean spectra and visually compare them and also compare the exact mz values. You could also plot both picked spectra with different colors in matplotlib in one plot to compare them.

If you do not need the matrix reduction anyway, you could also try to use the --merge option in the fast_conovert. In that case, the picker should pick on the overall mean of all samples. This might lead to sub-optimal picks in individual samples, i.e. you pick a value slightly next to the peak instead of the peak. This is also due to slight shifts, but there should be more similar mz values in that case.

**Comment by PeifengJi** [comment]
Thank you! I'll investigate this. What if I observe some minor shifts between the two samples? Should I change the pybasis parameters, for example increasing the tolerance, like setting mzmaxshift to 0.2 or cmzbinsize=0.002?

**Comment by Kawue** [comment]
There are various options. The first one would be what you just suggested, i.e. to improve the alignment by tuning the parameters. Did you apply the pyBASIS alignment to both data sets in one run or did you processed it individually? Because individual alignment would obviously be one of the problems here.
The second is to pick the values on the data sets individually and apply a shift procedure on your own. I am not aware of you programming skills. An example what you could try would be the following.

1. Pick individually.
2. Define a +- error window in which shifts are allowed. This depends on the resolution of you data. The higher the resolution the lower the error rate.
3. Merge the two picked lists and check: If two neighboring values are from different data sets and their difference is less than 'epsilon', adjust one of the values to the other or correct both of them to their mean.

In my opinion this would be an acceptable correction if the 'epsilon' is small enough. However, if your results will be published later on you will have to discuss this in detail, i.e. explain the choice to correct the data and the coice of your 'epsilon'. However, since an alignment is basically nothing else than 'shifting data around' I think such an procedure would be reasonable. However, for critical findings and if you are able to enrich your data with molecular identification, it might be a good argumentation to take the original values (X and Y) and the shifted value (Z). If X and Y cannot be identified as two different molecules and only one possible identification is reasonable between the interval of [X,Y] then I do not see any problems. Without the molecular identification the argumentation will be on a hypothetical level, which is always harder to justify.

Hope that helps.

**Comment by PeifengJi** [comment]
Thank you.
_1. If you do not need the matrix reduction anyway, you could also try to use the --merge option in the fast_conovert. In that case, the picker should pick on the overall mean of all samples._
I tried this in the python ~/Downloads/softs/provim/fast_convert_hdf.py -f basis/basis_processed_pybasis.h5 -s provim --write_merge. But, when using peak picking on the merged files:
 python ~/Downloads/softs/provim/workflow_peakpicking.py -r  provim/koLm083-koLm094-koLm241-koLm252-koPbs061-koPbs062-koPbs063-wtLm04-wtLm043-wtLm05-wtLm064-wtPbs02-wtPbs03-wtPbs103-wtPbs114_processed_simplified.h5 -s peakPicking --pick_on_merge -q

It raise error: 


I'm trying to trace back the code.

_2. Did you apply the pyBASIS alignment to both data sets in one run or did you processed it individually? Because individual alignment would obviously be one of the problems here._

I have run pybasis on all the samples at one time using the command: python ~/Downloads/softs/provim/workflow_pybasis.py -d data -s basis --multisample, where data is the directory containing all the imzML files of my project.


3. I think the theory behind your example is exactly like the alignment algorithm in pybasis, where the strategy is to increase the tolerance. Maybe I will firstly try increase the value of parameters.

**Comment by Kawue** [comment]
Well that error is interesting. Could you tell me the result of `df.index.names`where `df` is the loaded dataframe? Seems like the dataset index is defined multiple times, which should not be the case.

Regarding your third point, you are totally right. Its pretty much the same. However, implementing this only on the picked list does not increase the chance of misalignment for every peak in pixel and every sample, while incresing the tolerance in pybasis does.

You are also totally right with the weak alignment power of pybasis. Its a major weakness of the pipeline and a typical weakness for what we were interested in: 1. a fast algorithm with limited memory requirements and 2. an algorithm that is not too picky to allow the alignment of multiple samples.

The idea to create a reference peak list sounds promising to me, however, I never tried this with the pipeline.

**Comment by PeifengJi** [comment]
Hi, output as follows:
![Uploading 截屏2021-07-27 下午5.13.14.png…]()

This where I put the print() function in the /workflow_peakpicking.py,
<img width="1210" alt="截屏2021-07-27 下午6 33 10" src="https://user-images.githubusercontent.com/86214818/127140958-c4766d89-b408-4328-8caf-954c62331397.png">
  
It seems the problem was caused by the fast_convert_hdf.py.
I have tried to use Cardinal to check  ratio of the shared peaks between two samples, but, sadly, the result is also unsatisfied (even lower than that of pybasis). 
Totally agree with the point that alignment is an essential step for MSI data processing. What's more,  data processing of MSI data is a bottleneck of popularization of the MSI technology.

**Comment by Kawue** [comment]
Hmm interesting, could you compare the index values of the 'dataset' entries? You might get it with dframe.index.get_level_values(2) and dframe.index.get_level_values(3). If they are equal, we quickly hack this problem by deleting one of them. Just to progress with the code. The problem within fast_convert can be solved later.

On which data did you do the cardinal shared peaks stuff? Your original measurements I guess? In that case you would need to use an alignment using cardinal as well right?

**Comment by PeifengJi** [comment]
I think the method should work and will try it later. I have run cardinal on these two files generated by the peakpicking workflow. The peaks were aligned using cardinal with a tolerance of 10 ppm.Then peak lists were compared.

**Comment by Kawue** [comment]
But in that case you are biased by pyBASIS already, which might be a problem for cardinal right?
In theory you have to use the alignment of cardinal for the original data, then use cardinal for picking and thereafter check for shared peaks. Or am I missing something?

**Comment by PeifengJi** [comment]
Yes, but it really hard to choice. As cardinal normalize sample just using TIC or other normal statistic methods. So I set the shift of peals to 10 ppm. 
Currently, I plan to use shared peaks generated by the provim pipeline among samples for downstream analysis, like differential analysis, spatial variable metabolite detection.
Anyway, it would be good  if we adapt some methods or data frame (like Anndata) used in spatial transcriptome to perform normalization, batch effect removal, visualization. It will greatly benefit the community. 
Currently, I plan to use shared peaks generated by the provim pipeline among samples for downstream analysis, like differential analysis, spatial variable metabolite detection.
Anyway, it would be good  if we adapt some methods or data frame (like Anndata) used in spatial transcriptome to perform normalization, batch effect removal, visualization. It will greatly benefit the community.

**Comment by Kawue** [comment]
Totally agree. If I would start to actively work in the field again, the first thing I would do is to select an appropriate data structure and define standards for storage. The whole MSI storage thing is a mess.
I have to admit that Anndata, or at least something like that, looks slick for that purpose.

**Comment by PeifengJi** [comment]
Hi, I'm here to give a result of the pipeline.
Specifically, I firstly use pyBASIS to normalize my data (intra and inter). Then, fast_covert was used and to merge all the samples. Finally, I picked peaks from the merged file and gave rise to  a much better result than previous results. I think the peak picking algorithm works well on merged datasets to generate  a consensus peak list.
I think, this time, I can move to biological analysis.

**Comment by Kawue** [comment]
Awesome! I am glad everything worked out. If you run into new issues, let me know.
